V2.0
Hack-WashU/website2023 pull request #39
Opened 2023-08-01 03:45 UTC by EgeKeskin

2023-08-01 03:49 UTC, jackheuberger commented
Note to all reviewing: there's a file filter at the top to filter out all .png's lol

2023-08-01 04:13 UTC, jackheuberger requested changes
Looks GREAT. Love all the new images and the background. Here are some overall thoughts that aren't really file-specific:

- Overall sizing seems a little off on my screen, sections seem pretty large
- There's no mobile optimization. It looks fine on inspect element with a phone screen set, but it needs some more
- We should really try to shy away from encoding all the text as images if possible

2023-08-01 04:13 UTC, jackheuberger commented on src/assets/custom-images/divTracks/divisions.png
I think the glowing effect on the text makes this a little too busy in the context of the rest of the site
@emilyws27 @BradleyHsu thoughts?

2023-08-01 04:13 UTC, jackheuberger commented on src/assets/custom-images/header/main.png
I would love a way if we could typeset all of the words on the page rather than making them images, but I don't know what that would entail, @vinayvis821 ?

2023-08-01 04:13 UTC, jackheuberger commented on src/components/HeaderSection.vue
>          <img src="../assets/custom-images/header/main.png" alt="main planet" id="header-main-planet">
```suggestion
        <img src="../assets/custom-images/header/main.png" alt="large planet with text Hack WashU" id="header-main-planet">
```

2023-08-01 04:13 UTC, jackheuberger commented on src/assets/custom-images/divTracks/tracks.png
Same thing with legibility and also typesetting. If we decide to change things it would be nice not to have to change the entire graphic

@vinayvis821 could you take a crack at this mr. css wizard?

2023-08-01 04:13 UTC, jackheuberger commented on src/assets/Rectangle.png
Love the background, my only concern is what happens if we want to add more stuff to the page.

2023-08-01 04:13 UTC, jackheuberger commented on src/components/DivTracks.vue
nit: rename to Tracks from divTracks

2023-08-01 04:13 UTC, jackheuberger commented on src/assets/custom-images/faqSponsor/faq.png
This entire section either needs to be typeset into the site itself (in a way that's responsive to us needing to add/remove questions), or a link to some other page with event questions.

2023-08-01 04:13 UTC, jackheuberger commented on src/components/FaqSponsor.vue
I would split up into FAQ and Sponsor sections separately, if we start adding FAQs then this file will get gnarly quickly

2023-08-01 04:13 UTC, jackheuberger commented on src/assets/reset.css
> +	background: url('../assets//custom-images/Rectangle.jpg');
```suggestion
	background: url('../assets/custom-images/Rectangle.jpg');
```

2023-08-01 04:13 UTC, jackheuberger commented on src/faq.js
Don't worry about this -- I'll just rip what we had last year in some way. The problem is just the background being extendable based on how many questions there are

2023-08-02 03:30 UTC, emilyws27 commented on src/assets/custom-images/divTracks/divisions.png
I agree. I think it might be a little too hard to read too in conjunction with the distortion. Perhaps you can decrease the amount of "glow"? Like you can with a shadow.

2023-08-02 03:30 UTC, emilyws27 commented on src/assets/custom-images/header/main.png
Agreed. Would make it easier for us to update too w/ new info.

2023-08-02 03:33 UTC, emilyws27 commented
I agree with everything Jack says in terms of glow & converting the images to text... help @vinayvis821 !!!

I really love the design though and new font. It looks so good!!!! Thank you so much Sophia and Ege!!!!!!!!!! Only other thing I would add, and this might be extra af, but what if when you hover over the planets they move or smth. I can work on that now.

2023-08-02 03:34 UTC, EgeKeskin commented on src/assets/custom-images/header/main.png
I can convert images to text, I just gotta find the font for the large planets.

2023-08-02 03:36 UTC, EgeKeskin commented on src/assets/custom-images/divTracks/divisions.png
The glowing effect on which text?

2023-08-02 03:45 UTC, EgeKeskin commented on src/assets/custom-images/header/main.png
So I can convert the images to text for the stuff that isn't billboard esque for that we need @dykstrasophia to change (so tracks and division stuff).

2023-08-03 04:43 UTC, jackheuberger commented on src/assets/custom-images/divTracks/divisions.png
Divisions at the top

2023-08-19 18:16 UTC, jackheuberger approved these changes

2023-08-19 18:16 UTC, merged